language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - "android-sdk-preview-license-52d11cd2"
    - "android-sdk-license-.+"
    - "google-gdk-license-.+"

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
  - sudo sysctl -p

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

install:
  - nvm install 12
  - npm install
  - $(npm bin)/expo login -u ${EXPO_USER} -p ${EXPO_PWD}

script:
  - npm run eject
  - npm run link
  - npm run build

after_script:
  - $(npm bin)/expo logout

deploy:
  - provider: releases
    prerelease: true
    api_key: ${GH_TOKEN}
    file_glob: true
    file: esp-lights.apk
    skip_cleanup: true
    on:
      tags: true
      branch: master

  - provider: pages
    local_dir: dist/
    skip_cleanup: true
    github_token: ${GH_TOKEN}
    keep_history: true
    on:
      tags: true
      branch: master
