name: Expo build

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.6
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: npm install
        run: npm install

      - name: Expo eject
        run: npm run eject

      - name: React-native link
        run: npm run link

      - name: React-native build
        run: npm run build
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}


      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: esp-lights.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: esp-lights.apk
          token: ${{ secrets.GITHUB_TOKEN }}
